-- Copyright (C) 2016  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel MegaCore Function License Agreement, or other 
-- applicable license agreement, including, without limitation, 
-- that your use is for the sole purpose of programming logic 
-- devices manufactured by Intel and sold by Intel or its 
-- authorized distributors.  Please refer to the applicable 
-- agreement for further details.

-- Generated by Quartus Prime Version 16.1.0 Build 196 10/24/2016 SJ Lite Edition
-- Created on Tue Aug 04 20:32:20 2026

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY Traffic_Controller IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        timer_done : IN STD_LOGIC := '0';
        Green : OUT STD_LOGIC;
        Yellow : OUT STD_LOGIC;
        Red : OUT STD_LOGIC
    );
END Traffic_Controller;

ARCHITECTURE BEHAVIOR OF Traffic_Controller IS
    TYPE type_fstate IS (S0,S1,S2,S3);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,timer_done)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= S0;
            Green <= '0';
            Yellow <= '0';
            Red <= '0';
        ELSE
            Green <= '0';
            Yellow <= '0';
            Red <= '0';
            CASE fstate IS
                WHEN S0 =>
                    IF ((timer_done = '1')) THEN
                        reg_fstate <= S1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= S0;
                    END IF;

                    Red <= '0';

                    Yellow <= '0';

                    Green <= '1';
                WHEN S1 =>
                    IF ((timer_done = '1')) THEN
                        reg_fstate <= S2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= S1;
                    END IF;

                    Red <= '0';

                    Yellow <= '1';

                    Green <= '0';
                WHEN S2 =>
                    IF ((timer_done = '1')) THEN
                        reg_fstate <= S3;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= S2;
                    END IF;

                    Red <= '1';

                    Yellow <= '0';

                    Green <= '0';
                WHEN S3 =>
                    IF ((timer_done = '1')) THEN
                        reg_fstate <= S0;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= S3;
                    END IF;

                    Red <= '0';

                    Yellow <= '1';

                    Green <= '0';
                WHEN OTHERS => 
                    Green <= 'X';
                    Yellow <= 'X';
                    Red <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
